### ISSUE TITLE
Do we need to codify the difference between PUREs and Issues?

### ISSUE THREAD

**Issue by jhdalek55** [uptane/pures#6]
Last November, in connection with a PR that was making a minor fix on the Participate page of the website repo, I raised the issue of whether we needed to distinguish between which proposed changes should be submitted as Issues and which should be submitted as PUREs. I was planning to add some text at the time but in wrapping up end of year projects, unfortunately, lost track of the PR it was attached to. I have now merged the existing PR #, but wanted to maintain this question.

Should we add something to either PURE 1, or the README for the PUREs making this distinction...and perhaps also post it in the README for the Standard? I took a quick look and it appears neither TUF nor in-toto have this text. But, our potential Uptane contributors may not be as familiar with this type of mechanism (which I'm assuming is more of an open source mechanism). Perhaps it wouldn't hurt to overstate what might seem obvious...

Thoughts?

**Comment by jhdalek55** [comment]
This has been sitting here without comment since the spring. I would appreciate some feedback on whether we need to spell out the types of changes we develop as PUREs.

**Comment by pattivacek** [comment]
My suggestion is that everything should start as an issue, in order to raise attention and start a discussion. PUREs are presumably for bigger changes, particularly optional things that may not be desirable for all implementers due to complexity or other tradeoffs. But if the desired change is smaller, just fixing a bug or clarifying an edge case, raising an issue or just going straight to a PR is probably best.

**Comment by JustinCappos** [comment]
I'd second Patti's suggestion.  In TUF, we typically reserve TAPs for
things that are substantial specification changes, such as adding a new
feature or changing a part of the way the system works.  Issues are for
minor clarifications around corner cases, changing a SHOULD to a MUST, etc.

**Comment by jhdalek55** [comment]
See PR# 7

**Comment by jhdalek55** [comment]
Fixed with PR#7
